### ISSUE TITLE
Crash when setStatusBarColor: dialog must not be null

### ISSUE THREAD

**Issue by anticafe** [andrefrsousa/SuperBottomSheet#21]
Crash log:
```
Fatal Exception: java.lang.IllegalStateException: dialog must not be null
       at com.andrefrsousa.superbottomsheet.SuperBottomSheetFragment.setStatusBarColor(SourceFile:3)
       at com.andrefrsousa.superbottomsheet.SuperBottomSheetFragment.setStatusBarColorOnScroll(SourceFile:5)
       at com.andrefrsousa.superbottomsheet.SuperBottomSheetFragment.access$setStatusBarColorOnScroll(SourceFile:1)
       at com.andrefrsousa.superbottomsheet.SuperBottomSheetFragment$iniBottomSheetUiComponents$3.onSlide(SourceFile:2)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.dispatchOnSlide(SourceFile:6)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$3.onViewPositionChanged(SourceFile:1)
       at f.j.a.c.n(SourceFile:9)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(SourceFile:1)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:5730)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
```

Device: 100% OPPO phone. For now only see Android 5 & 6.

**Comment by andrefrsousa** [comment]
Fixed on [version 2.0.0](https://github.com/andrefrsousa/SuperBottomSheet/releases/tag/2.0.0)
